import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-screen h-screen">
      <div className="flex gap-[48px] py-[20px] w-full justify-center items-center">
        {children}
        <>
          <Image
            className="rounded-2xl"
            src={"/guy.png"}
            width={856}
            height={904}
            alt="poster"
          />
        </>
      </div>
    </div>
  );
}
